---
title: "glm-covid19-build-data"
author: "Xinyuan Zheng xz2906"
date: "5/16/2020"
output: pdf_document
---

## By Age group

```{r}
# by-age 
# 3.28 3.29 missing
age.path <- c(paste("nyc.gov/",3, ".",c(26,27,30,31),"/by-age.csv", sep =""),
              paste("nyc.gov/",4, ".",c(1:30),"/by-age.csv", sep =""),
              paste("nyc.gov/",5, ".",c(1:15),"/by-age.csv", sep =""))

age.dfname <- c(paste("Mar.",c(26,27,30,31),".age",sep =""),
              paste("Apr.",c(1:30), ".age", sep =""),
              paste("May.",c(1:15),".age", sep =""))

date.dfname <- c(paste("Mar.",c(26,27,30,31),sep =""),
              paste("Apr.",c(1:30), sep =""),
              paste("May.",c(1:15), sep =""))

# read the csv files separately in matrixs
for (i in 1:length(age.path)) {
  assign(age.dfname[i], read.csv(age.path[i]))
}
# read the files in one list
age.list <- vector(mode = "list", length = length(age.path))
for (i in 1:length(age.path)){
  age.list[[i]] <- read.csv(age.path[i])
}
```


```{r} 
# For Mar.26
# assume the death rate of 0-17 years on Mar 26 is 0
Mar.26.age[1,"DEATH_RATE"] <- 0 
# Haldane-Anscombe correction to fix 0 cell
# add 0.5 to each cell of contingency table, i.e. add 0.5/100000 to rates per 100,000 people
Mar.26.age[,-1] <- Mar.26.age[,-1] + 0.5/100000
#fix for Mar.27 too!
age.list[[2]][,-1] <- age.list[[2]][,-1] + 0.5/100000
```


## By Gender Group

```{r}
# by-gender
# 3.28 3.29 missing
sex.path <- c(paste("nyc.gov/",3, ".",c(26,27,30,31),"/by-sex.csv", sep =""),
              paste("nyc.gov/",4, ".",c(1:30),"/by-sex.csv", sep =""),
              paste("nyc.gov/",5, ".",c(1:15),"/by-sex.csv", sep =""))

# read the files in one list
sex.list <- vector(mode = "list", length = length(sex.path))
for (i in 1:length(sex.path)){
  sex.list[[i]] <- read.csv(sex.path[i])
}
```


