---
title: "ORs"
author: "Xinyuan Zheng xz2906"
date: "5/17/2020"
output: pdf_document
---

```{r}
# Please first run build-data-ORs to create variables in your environment
```


```{r}
# EDA age0-17
age17.OR <- matrix(NA,ncol=3,nrow=length(age.path))

for (i in 1:(length(age.path))){
  mat <- age.ORlist[[i]]
  age17.OR[i,] <- mat[1,]
}

library(miscTools)

my.df <- as.matrix(age17.OR)
my.vec <- rep(NA,3)
new.df <- insertRow(my.df,3,my.vec)
age17.OR <- insertRow(new.df,3,my.vec)

plot(age17.OR[,1],x=c(1:51),"l")
```



```{r}
# case / hos
(Mar.26.age[,2]/Mar.26.age[,3])
# younger people get more hospitalization per case
# all ORs on Mar 26
Mar.26.OR <- matrix(NA, ncol=3, nrow=5)
colnames(Mar.26.OR) <- c("case","hos","death")
for (j in 2:4){
#  total <- (Mar.26.age[6,j]/(100000-Mar.26.age[6,j]))

  age17 <- (Mar.26.age[1,j]/(100000-Mar.26.age[1,j]))
  age44 <- (Mar.26.age[2,j]/(100000-Mar.26.age[2,j]))
  age64 <- (Mar.26.age[3,j]/(100000-Mar.26.age[3,j]))
  age74 <- (Mar.26.age[4,j]/(100000-Mar.26.age[4,j]))
  age75Older <- (Mar.26.age[5,j]/(100000-Mar.26.age[5,j]))
  
  Mar.26.OR[,j-1] <- c(age17,age44,age64,age74,age75Older)/age17
  Mar.26.OR <- round(Mar.26.OR,6)
}
```


```{r}
# ORs by age all dates
age.ORlist <- vector(mode = "list", length = length(age.path))

for (i in 1:length(age.path)){
  
  # init a 3X5 matrix for each date's ORs
  OR <- matrix(NA, ncol=3, nrow=5)
  colnames(OR) <- c("case","hos","death")
  df <- age.list[[i]] #data for each date in a df
  
    for (j in 2:4){
#    total <- (df[6,j]/(100000-df[6,j]))
  
    age17 <- (df[1,j]/(100000-df[1,j]))
    age44 <- (df[2,j]/(100000-df[2,j]))
    age64 <- (df[3,j]/(100000-df[3,j]))
    age74 <- (df[4,j]/(100000-df[4,j]))
    age75Older <- (df[5,j]/(100000-df[5,j]))
    
    OR[,j-1] <- c(age17,age44,age64,age74,age75Older)/age17
    OR <- round(OR,6) # ORs for ith date
    }
  age.ORlist[[i]] <- OR
}

age.ORlist[[1]] <- Mar.26.OR

names(age.ORlist) <- date.dfname
```



```{r}
# OR by Age Groups Trend Plots -cases
par(mfrow=c(2,2), mar=c(3,3,2,2))

age44.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age44.case.OR[i] <- age.ORlist[[i]][2,1]
}
plot(age44.case.OR,type="l",main="Daily Cases Age44-18/Age0-17 ORs Trend")


age64.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age64.case.OR[i] <- age.ORlist[[i]][3,1]
}
plot(age64.case.OR,type="l",main="Daily Cases Age45-64/Age0-17 ORs Trend")


age74.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age74.case.OR[i] <- age.ORlist[[i]][4,1]
}
plot(age74.case.OR,type="l",main="Daily Cases Age65-74/Age0-17 ORs Trend")


age75Older.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age75Older.case.OR[i] <- age.ORlist[[i]][5,1]
}
plot(age75Older.case.OR,type="l",main="Daily Cases Age65-74/Age00-17 ORs Trend")
```


```{r}
# OR by Age Groups Trend Plots -deaths
par(mfrow=c(2,2), mar=c(3,3,2,2))

age44.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age44.case.OR[i] <- age.ORlist[[i]][2,3]
}
plot(age44.case.OR,type="l",main="Daily Cases Age44-18/Age0-17 ORs Trend")


age64.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age64.case.OR[i] <- age.ORlist[[i]][3,3]
}
plot(age64.case.OR,type="l",main="Daily Cases Age45-64/Age0-17 ORs Trend")


age74.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age74.case.OR[i] <- age.ORlist[[i]][4,3]
}
plot(age74.case.OR,type="l",main="Daily Cases Age65-74/Age0-17 ORs Trend")


age75Older.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  age75Older.case.OR[i] <- age.ORlist[[i]][5,3]
}
plot(age75Older.case.OR,type="l",main="Daily Cases Age65-74/Age00-17 ORs Trend")
# nearly no deaths in age group 0-17
```

```{r}
# ORs by age all dates
sex.ORlist <- vector(mode = "list", length = length(sex.path))

for (i in 1:length(sex.path)){
  df <- sex.list[[i]] #data for each date in a df
  
  # init a vector to store case hospitalization and death ORs 
  OR <- rep(NA, 3)
  names(OR) <- c("case","hos","death")
  
  for (j in 2:4){
    female.odds <- df[1,j]/(100000-df[1,j])
    male.odds <- df[2,j]/(100000-df[2,j])
    OR[j-1] <- female.odds/male.odds
  }
  OR <- round(OR,6) # ORs for ith date
  sex.ORlist[[i]] <- OR
}

names(sex.ORlist) <- date.dfname
```


```{r}
gender.case.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  gender.case.OR[i] <- sex.ORlist[[i]][1]
}
plot(gender.case.OR,type="l",main="Daily Cases by Gender Odds Ratios Trend")
```


```{r}
gender.death.OR <- rep(NA,length(sex.ORlist))
for (i in 1:length(sex.ORlist)){
  gender.case.OR[i] <- sex.ORlist[[i]][3]
}
plot(gender.case.OR,type="l",main="Death by Gender Odds Ratios Trend")
# In the first a few days there are not many deaths 
```

