---
title: "model"
author: "Xinyuan Zheng xz2906"
date: "5/17/2020"
output: pdf_document
---




################


```{r}
glm0 <- glm(case~order+test+
              lag1+lag2+lag3+
              hoslag1+hoslag1+hoslag3, 
            data = train, family = "poisson")
summary(glm0)
pred.case0 <- predict(glm0,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case0, col = "blue",lwd=2)
```


```{r}
glm1 <- glm(case~order+test+lag3+hoslag3, data = train, family = "poisson")
summary(glm1)
pred.case1 <- predict(glm1,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case1, col = "blue", lwd=2)
```

```{r}
glm2 <- glm(case~order+test+lag2+hoslag2, data = train, family = "poisson")
summary(glm2)
pred.case2 <- predict(glm2,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case2, col = "blue", lwd=2)
```


```{r}
glm.pois <- glmnet(y = train$case, x = as.matrix(train[,5:9]), family="poisson", alpha=0)
summary(glm.pois)
temp = as.matrix(train[,5:9])

predict(glm.pois, newx=rep(0,5),type="response")

plot(glm.data$case, type = "l")
lines(c(1:dim(train)[1]), pred.glm.pois, col = "red")

```


```{r}
CASES_now~CASES_lag4+TEST+MOB+MOB_IND+PROV, data = dat.combine,
          level = 2,               # pairwise interaction considered
          method = "h",            # Exhaustive approach
          crit = "bic",            # BIC as criteria
          confsetsize = 10,        # Keep 10 best models
          plotty = F, report = F,  # Plot or interim reports
          fitfunction = glm.pois)
```

glm.pois <- glmnet(D, Y_cv, family='poisson', lambda = lambda0 + 1, alpha=alpha,  maxit=1000000, standardize=TRUE)




```{r}
glmulti.pois.out <-
  glmulti(CASES_now~CASES_lag4+TEST+MOB+MOB_IND+PROV, data = dat.combine,
          level = 2,               # pairwise interaction considered
          method = "h",            # Exhaustive approach
          crit = "bic",            # BIC as criteria
          confsetsize = 10,        # Keep 10 best models
          plotty = F, report = F,  # Plot or interim reports
          fitfunction = glm.pois)
```

