---
title: "models"
author: "Xinyuan Zheng xz2906"
date: "5/17/2020"
output: pdf_document
---

```{r}
# Please first run build-data-glm to create variables in your environment
```


```{r}
library(glmnet)
```


```{r}
# using all predictors
glm0 <- glm(case~order+test+
              lag1+lag2+lag3+
              hoslag1+hoslag1+hoslag3, 
            data = train, family = "poisson")
summary(glm0) # AIC: 33256
plot(glm0)
pred.case0 <- predict(glm0,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case0, col = "blue",lwd=2)
```


```{r}
# lag3
glm1 <- glm(case~order+test+lag3+hoslag3, data = train, family = "poisson")
summary(glm1) # AIC: 49367
plot(glm1)
pred.case1 <- predict(glm1,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case1, col = "blue", lwd=2)
```


```{r}
# lag2
glm2 <- glm(case~order+test+lag2+hoslag2, data = train, family = "poisson")
summary(glm2) # AIC: 46773
plot(glm2)
pred.case2 <- predict(glm2,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case2, col = "blue", lwd=2)
```


```{r}
glm3 <- glm(case~order+test+lag2+hoslag2+
              lag2*hoslag2+
              lag2*test+
              hoslag2*test+
              order*lag2+
              order*hoslag2, 
            data = train, family = "poisson")
summary(glm3) # AIC: 25555
plot(glm3)
pred.case3 <- predict(glm3,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case3, col = "blue", lwd=2)
```


```{r}
# keep significant interaction terms
glm4 <- glm(case~order+test+lag2+hoslag2+
              lag2*hoslag2+
              test*lag2+
              test*hoslag2+
              order*hoslag2,
            data = train, family = "poisson")
summary(glm4) # AIC: 25553
plot(glm4)
pred.case4 <- predict(glm4,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case4, col = "blue", lwd=2)
```


```{r}
glm5 <- glm(case~order+test+lag2+hoslag2+
              lag2*hoslag2+
              test*lag2+
              order*hoslag2,
            data = train, family = "poisson")
summary(glm5) # AIC: 25554
plot(glm5)
pred.case5 <- predict(glm5,type="response")

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines(c(1:dim(train)[1]), pred.case5, col = "blue", lwd=2)
```


####################

```{r}
library(glmnet)
# to include interactions
f <- as.formula(case~order+test+lag2+hoslag2+
              lag2:hoslag2+
              test:lag2+
              order:hoslag2)
# transform dataframe to matrices as required by glmnet
x <- model.matrix(f, train)
t <- model.matrix(f, test)
y <- as.matrix(train$case, ncol=1)
```



```{r}
# rigid
require(methods)
cvglm <- cv.glmnet(x, y, alpha = 0, lambda = 10^seq(-3,3,by =.1), nfolds = 10) 
summary(cvglm)
plot(cvglm)
coef(cvglm)

l <- cvglm$lambda.min
cv.err <- cvglm$cvm[which.min(cvglm$cvm)] #704375.3

pred.cvglm <- predict(cvglm, newx=t)
plot(glm.data$case, type = "l", ylim = c(0,8000))
ind <- c(dim(train)[1]+1):(dim(train)[1]+dim(test)[1])
lines(ind, pred.cvglm, col = "blue", lwd=2)

#RSS
RSS <- sum((pred.cvglm-glm.data$case[ind])^2) #2694339
```


```{r}
# # using fewer folds
# require(methods)
# cvglm <- cv.glmnet(x, y, alpha = 0, lambda = 10^seq(-3,3,by =.1), nfolds=5)
# summary(cvglm)
# plot(cvglm)
# 
# l <- cvglm$lambda.min
# cv.err <- cvglm$cvm[which.min(cvglm$cvm)] #687815.6
# 
# pred.cvglm <- predict(cvglm, newx=t)
# plot(glm.data$case, type = "l", ylim = c(0,8000))
# ind <- c(dim(train)[1]+1):(dim(train)[1]+dim(test)[1])
# lines(ind, pred.cvglm, col = "blue", lwd=2)
# 
# #RSS
# RSS <- sum((pred.cvglm-glm.data$case[ind])^2) #2957421
```


```{r}
# # lasso
# cvglm2 <- cv.glmnet(x, y, alpha = 1, lambda = 10^seq(-3,3,by =.1), nfolds= 20)
# summary(cvglm2)
# plot(cvglm2)
# 
# l2 <- cvglm2$lambda.min
# pred.cvglm2 <- predict(cvglm2, newx=t)
# cv.err2 <- cvglm2$cvm[which.min(cvglm2$cvm)] #666189.9
# 
# plot(glm.data$case, type = "l", ylim = c(0,8000))
# lines((dim(train)[1]+1):(dim(train)[1]+dim(test)[1]), pred.cvglm2, col = "blue", lwd=2)
# 
# #RSS
# RSS2 <- sum((pred.cvglm2-glm.data$case[ind])^2) #1293788
```



```{r}
# lasso
cvglm2 <- cv.glmnet(x, y, alpha = 1, lambda = 10^seq(-3,3,by =.1))
summary(cvglm2)
plot(cvglm2)

l2 <- cvglm2$lambda.min
pred.cvglm2 <- predict(cvglm2, newx=t)
cv.err2 <- cvglm2$cvm[which.min(cvglm2$cvm)] #674864.3

plot(glm.data$case, type = "l", ylim = c(0,8000))
lines((dim(train)[1]+1):(dim(train)[1]+dim(test)[1]), pred.cvglm2, col = "blue", lwd=2)

#RSS
RSS2 <- sum((pred.cvglm2-glm.data$case[ind])^2) #1275282
```


```{r}
# # lasso
# cvglm2 <- cv.glmnet(x, y, alpha = 1, lambda = 10^seq(-3,3,by =.1), nfolds = 7)
# summary(cvglm2)
# plot(cvglm2)
# 
# l2 <- cvglm2$lambda.min
# pred.cvglm2 <- predict(cvglm2, newx=t)
# cv.err2 <- cvglm2$cvm[which.min(cvglm2$cvm)] #691746.7
# 
# plot(glm.data$case, type = "l", ylim = c(0,8000))
# lines((dim(train)[1]+1):(dim(train)[1]+dim(test)[1]), pred.cvglm2, col = "blue", lwd=2)
# 
# #RSS
# RSS2 <- sum((pred.cvglm2-glm.data$case[ind])^2) #1525892
```

