---
title: "glm-covid19-build-data"
author: "Xinyuan Zheng xz2906"
date: "5/16/2020"
output: pdf_document
---

```{r}
Mar26_boro <- read.csv("nyc.gov/3.26/boro.csv")
```

```{r}
#by-age 
#3.28 3.29 missing
age.path <- c(paste("nyc.gov/",3, ".",c(26,27,30,31),"/by-age.csv", sep =""),
              paste("nyc.gov/",4, ".",c(1:30),"/by-age.csv", sep =""),
              paste("nyc.gov/",5, ".",c(1:15),"/by-age.csv", sep =""))

age.dfname <- c(paste("Mar.",c(26,27,30,31),".age",sep =""),
              paste("Apr.",c(1:30), ".age", sep =""),
              paste("May.",c(1:15),".age", sep =""))

for (i in 1:length(age.path)) {
  assign(age.dfname[i], read.csv(age.path[i]))
}

read.csv("summary.csv")
```

```{r}
Mar.26.age[1,"DEATH_RATE"] <- 0 # assume the death rate of 0-17 years on Mar 26 to be 0
# Haldane-Anscombe correction to fix 0 cell
# add 0.5 to each cell of contingency table, i.e. add 0.5/100000 to rates per 100,000 people
Mar.26.age[,-1] <- Mar.26.age[,-1] + 0.5/100000
Mar.26.age
```











