---
title: "ts-analysis"
author: "Xinyuan Zheng xz2906"
date: "5/17/2020"
output: pdf_document
---

```{r}
library(forecast)
```

```{r}
data <- read.csv("nyc.gov/5.15/case-hosp-death.csv")

for (i in 1:dim(data)[1]){
  data$accum_case[i] <- sum(data[1:i,2])
  data$accum_death[i] <- sum(data[1:i,4])
}

case.ts <- data[,2]
accumcase.ts <- data[,5]
death.ts <- data[,4]
accum_death.ts <- data[,6]
```


```{r}
# create a daily Date 
date.inds <- seq(as.Date("2020-02-29"), as.Date("2020-5-14"), by = "day")
start.date <- as.numeric(format(date.inds[1], "%j"))
# create the time series
case.ts <- ts(case.ts, start=c(2020,start.date), frequency=365)
accumcase.ts <- ts(accumcase.ts, start=c(2020,start.date), frequency=365)
death.ts <- ts(death.ts, start=c(2020,start.date), frequency=365)
accum_death.ts <- ts(accum_death.ts, start=c(2020,start.date), frequency=365)
```


```{r}
# plots
par(mfrow=c(2,2), mar=c(3,3,2,3))
plot.ts(case.ts, main="daily cases")
plot.ts(accumcase.ts, main="total cases")
plot.ts(death.ts, main="daily deaths")
plot.ts(accum_death.ts, main="total deaths")
```


```{r}
# case
exp.model.case <- ets(case.ts)
# Returns best ARIMA model according to either AIC, AICc or BIC value. 
# The function conducts a search over possible model within the order constraints provided.
arma.model.case <- auto.arima(case.ts, stepwise = F, approximation = F)

exp.model.case
#accuracy(exp.model.case)
arma.model.case
#accuracy(arma.model.case)
arimaorder(arma.model.case) # 1 1 3 
```


```{r}
# death
exp.model.death <- ets(death.ts)
arma.model.death <- auto.arima(death.ts, stepwise = F, approximation = F)

exp.model.death
#accuracy(exp.model.death)
arma.model.death
#accuracy(arma.model.death)
arimaorder(arma.model.death) # 0 2 5 
```






```{r}
glmulti.pois.out <-
  glmulti(CASES_now~CASES_lag4+TEST+MOB+MOB_IND+PROV, data = dat.combine,
          level = 2,               # pairwise interaction considered
          method = "h",            # Exhaustive approach
          crit = "bic",            # BIC as criteria
          confsetsize = 10,        # Keep 10 best models
          plotty = F, report = F,  # Plot or interim reports
          fitfunction = glm.pois)
```

